require.config({
    paths:{
        jquery:'./jquery',
        detail:'./lib/detail',
        cookie:'./lib/cookie'
    },
    shim:{}
})

require(['jquery','detail','cookie'],function($,detail){
    detail.getdata(function(res){
        detail.change(res,function(){
            detail.detail()
        });
        $('.add').on('click',function(){
            detail.addItem(res.id,res.price,$('.number').val());
        })
    })
})